-- 1. Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, NOW()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 3. Create policy to allow anonymous inserts
-- We use DO block to check if policy exists to avoid error on repeated runs
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE tablename = 'messages'
        AND policyname = 'Allow anon insert'
    ) THEN
        CREATE POLICY "Allow anon insert" 
        ON public.messages 
        FOR INSERT 
        TO anon 
        WITH CHECK (true);
    END IF;
END
$$;

-- 4. Grant access to anon role (Supabase specific, but good for general Postgres web setups if using anon role)
GRANT INSERT ON public.messages TO anon;
GRANT USAGE, SELECT ON SEQUENCE messages_id_seq TO anon;
